version: '3.7'

services:
  #MySQL
  db:
    image: library/mysql:5.7
    environment:
      MYSQL_DATABASE: 'camping-fire'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    networks:
      - mysql-network
  #phpMyAdmin
  app:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=1234
    ports:
      - '80:80'
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge