# Server Configuration
server:
  port: 8080

# Logs Configuration
logging:
  file:
    path: logs/
    name: logs/camping-fire.log

spring:
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    show-sql: true
  # H2 Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Configuration
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:camping_fire
    initialization-mode: always
    driver-class-name: org.h2.Driver
  # Servlet Configuration
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB