# Server Configuration
server:
  port: 8080

spring:
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    show-sql: true
  # Database Configuration
  datasource:
    url: mysql://bb32289faa17ca:78939316@us-cdbr-east-02.cleardb.com/heroku_b29d43ded63568a?reconnect=true
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
  # Servlet Configuration
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB