# Server Configuration
server:
  port: 8080

spring:
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    show-sql: true
  # Database Configuration
  datasource:
    username: root
    password: camping-fire
    url: jdbc:mysql://35.198.4.20:3306/camping_fire?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&useSSL=false
    #initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
  # Servlet Configuration
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB